### ISSUE TITLE
Compare performance of GeoPandas vs current method

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/fws-nwi#12]

**Comment by m-mohr** [comment]
fyi: Geopandas ran out of memory for me (~12 GB)

**Comment by gadomski** [comment]
Current method:

```
stac fws-nwi create-item ~/Desktop/SD_shapefile_wetlands.zip out.json  609.91s user 31.91s system 97% cpu 10:55.42 total
```

Just using geopandas:

```
python geopandas_test.py  270.25s user 27.23s system 93% cpu 5:17.54 total
```

So about half the time (excepting that the create-item code is doing extra work, but I'm assuming that the conversion is the bulk).

@m-mohr was there a state that blew up your memory? South Dakota isn't the biggest but it isn't the smallest either.

**Comment by m-mohr** [comment]
Can't remember, maybe try the largest file?
Could also be that geopandas got an update to work with less memory or your computer has more memory available (I had usually around 10GB for it).

**Comment by gadomski** [comment]
Yeah, I just tried it on California, the biggest, and peaked at about 7GB. Still pretty beefy.
